version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "UserGateWay"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rhs4uizc3gqq"
s3_prefix = "UserGateWay"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
